// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiwgzkluwtwzmuvwmdym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpd2d6a2x1d3R3em11dndtZHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMDU3NzIsImV4cCI6MjA4OTY4MTc3Mn0.bE_XzgPVXMFM-QwmiGAbU1w6mHCl2Jk_QwtJJPQuOwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});